version: '3.6'

services:
  db:
    image: postgres:14-bullseye
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=plebbid
      - POSTGRES_USER=pleb
      - POSTGRES_PASSWORD=plebpass
    networks:
      - db_network
  api:
    build: .
    depends_on: [db]
    restart: on-failure
    stop_grace_period: 1m
    networks:
      - db_network
      - proxy
