version: '3.6'

services:
  api:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/healthcheck" ]
      interval: 3s
      timeout: 3s
      retries: 5
  test:
    build: .
    depends_on:
      api:
        condition: service_healthy
    environment:
      - FLASK_APP=plebbid.main
      - BASE_URL=http://api:5000
    volumes:
      - "./plebbid:/app/plebbid"
    networks:
      - proxy
    command: flask run-tests

networks:
  proxy:
    driver: bridge
