version: '3.6'

services:
  db:
    volumes:
      - "/home/www/plebeianmarket-dbdata:/var/lib/postgresql/data"
  api:
    environment:
      - JOB=WEB
      - VIRTUAL_HOST=api.plebeian.market
      - LETSENCRYPT_HOST=api.plebeian.market
      - LND_GRPC=plebeian.m.voltageapp.io:10009
    volumes:
      - "/home/www/plebeianmarket-secrets:/secrets"
  settle-bids:
    environment:
      - JOB=SETTLE_BIDS
      - FLASK_APP=plebeianmarket.main
      - LND_GRPC=plebeian.m.voltageapp.io:10009
    volumes:
      - "/home/www/plebeianmarket-secrets:/secrets"

networks:
  proxy:
    external: true
