version: '3.6'

services:
  db:
    volumes:
      - "/home/www/plebeian-market-dbdata:/var/lib/postgresql/data"
  web:
    environment:
      - LND_GRPC=plebeian.m.voltageapp.io:10009
    volumes:
      - "/home/www/plebeian-market-secrets:/secrets"
    command: gunicorn --chdir /app server.main:app -w 2 --threads 2 -b 0.0.0.0:8080
  nginx:
    build:
      context: ./
      dockerfile: ./services/nginx/Dockerfile
    environment:
      - VIRTUAL_HOST=plebeian.market
      - LETSENCRYPT_HOST=plebeian.market
    depends_on:
      - web
    networks:
      - proxy
  settle-bids:
    environment:
      - FLASK_APP=server.main
      - LND_GRPC=plebeian.m.voltageapp.io:10009
    volumes:
      - "/home/www/plebeian-market-secrets:/secrets"
    command: flask settle-bids

networks:
  proxy:
    external: true
