version: '3.6'

services:
  test:
    image: plebeianmarket-server
    depends_on:
      api:
        condition: service_healthy
    environment:
      - FLASK_APP=main
      - BASE_URL=http://api:5000
    volumes:
      - "./server:/app/server"
    networks:
      - proxy
    command: flask run-tests
