version: '3.6'

services:
  test:
    build: .
    depends_on:
      api:
        condition: service_healthy
    environment:
      - FLASK_APP=plebeianmarket.main
      - BASE_URL=http://api:5000
    volumes:
      - "./plebeianmarket:/app/plebeianmarket"
    networks:
      - proxy
    command: flask run-tests

networks:
  proxy:
    driver: bridge
